"""create projects table

Revision ID: 5ed986499ebc
Revises: abc49a85fd63
Create Date: 2026-04-29 01:39:31.731042

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5ed986499ebc"
down_revision: str | None = "abc49a85fd63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("client_name", sa.String(length=120), nullable=True),
        sa.Column("staging_url", sa.String(length=2048), nullable=True),
        sa.Column("production_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "in_progress",
                "completed",
                "archived",
                name="project_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
