"""add audit_diffs table and companion link

Revision ID: 68af16cfeeb5
Revises: cdf75be2ec2e
Create Date: 2026-04-29 02:31:28.066577

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "68af16cfeeb5"
down_revision: str | None = "cdf75be2ec2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_diffs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("audit_id", sa.String(length=36), nullable=False),
        sa.Column("page_url", sa.String(length=2048), nullable=False),
        sa.Column("field", sa.String(length=80), nullable=False),
        sa.Column("staging_value", sa.Text(), nullable=True),
        sa.Column("production_value", sa.Text(), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum(
                "added_in_production",
                "removed_in_production",
                "modified",
                name="diff_change_type",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "critical",
                "warning",
                "info",
                "ok",
                name="issue_severity",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["audits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_diffs_audit_id"), "audit_diffs", ["audit_id"], unique=False)
    op.add_column("audits", sa.Column("companion_audit_id", sa.String(length=36), nullable=True))
    op.add_column(
        "audits",
        sa.Column(
            "verdict",
            sa.Enum("go", "no_go", name="audit_verdict", native_enum=False, length=10),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_audits_companion_audit_id"), "audits", ["companion_audit_id"], unique=False
    )
    op.create_foreign_key(
        None, "audits", "audits", ["companion_audit_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "audits", type_="foreignkey")
    op.drop_index(op.f("ix_audits_companion_audit_id"), table_name="audits")
    op.drop_column("audits", "verdict")
    op.drop_column("audits", "companion_audit_id")
    op.drop_index(op.f("ix_audit_diffs_audit_id"), table_name="audit_diffs")
    op.drop_table("audit_diffs")
    # ### end Alembic commands ###
