"""create audits and audit_issues tables

Revision ID: cdf75be2ec2e
Revises: 5ed986499ebc
Create Date: 2026-04-29 02:12:26.340272

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "cdf75be2ec2e"
down_revision: str | None = "5ed986499ebc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column(
            "environment",
            sa.Enum(
                "production", "staging", name="audit_environment", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                name="audit_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("pages_crawled", sa.Integer(), nullable=False),
        sa.Column("broken_links_count", sa.Integer(), nullable=False),
        sa.Column("seo_score", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audits_project_id"), "audits", ["project_id"], unique=False)
    op.create_table(
        "audit_issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("audit_id", sa.String(length=36), nullable=False),
        sa.Column("page_url", sa.String(length=2048), nullable=False),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "critical",
                "warning",
                "info",
                "ok",
                name="issue_severity",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["audit_id"], ["audits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_issues_audit_id"), "audit_issues", ["audit_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_issues_audit_id"), table_name="audit_issues")
    op.drop_table("audit_issues")
    op.drop_index(op.f("ix_audits_project_id"), table_name="audits")
    op.drop_table("audits")
    # ### end Alembic commands ###
